In [1]:
print("hello")

hello


In [2]:
! pip3 install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 5.3 MB 5.1 MB/s eta 0:00:01
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.


In [2]:
import numpy as np


In [3]:
x = np.arange(5)
print(x)


[0 1 2 3 4]


In [7]:
marks = np.array([92,61,45,78,33,55])
print(np.where(marks>75,"A",np.where((marks>=50) & (marks<=75),"B","C")))

['A' 'B' 'C' 'A' 'C' 'B']


In [8]:
marks = np.array([92,61,45,78,33,55])
idx = np.where(marks > 50)[0]
print("raw return:",idx)

raw return: [0 1 3 5]


In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("a * b  :",a*b)
print("np.dot :",np.dot(a,b))
print("a @ b  :",a@b)

a * b  : [ 4 10 18]
np.dot : 32
a @ b  : 32


In [14]:
x = np.array([[1, 2, 3],[4, 5, 6]])
y = np.array([[3,5],[5,6],[7,8]])
print(x)
print(x.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [15]:
x = np.array([[1, 2, 3],[4, 5, 6]])
y = np.array([[3,5],[5,6],[7,8]])

print(x@x.T)

[[14 32]
 [32 77]]


In [40]:
s1 = [72,85,60,91]
s2 = [45,30,98,55]
s3 = [88,66,74,100]
f = np.array((s1,s2,s3))
old = np.array([['62','71','55','80'],
                ['49','58','66','73']])
print("no of student",f.shape[0])
print("no of subjects",f.shape[1])
print("total no of marks entries ",np.size(f))
print("total sum ",np.sum(f))
print(f.astype('float32'))
old = old.astype("int32")
print("converted into int ",old)
f = np.vstack((f,old))
print("combined both array",f)


no of student 3
no of subjects 4
total no of marks entries  12
total sum  864
[[ 72.  85.  60.  91.]
 [ 45.  30.  98.  55.]
 [ 88.  66.  74. 100.]]
converted into int  [[62 71 55 80]
 [49 58 66 73]]
combined both array [[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]
 [ 62  71  55  80]
 [ 49  58  66  73]]


In [61]:
sheet = np.zeros((6,4),dtype='int32')
tem = np.full((6,4),35)
arr = np.arange(101,130,2)
print(arr)
arr1 = np.linspace(0,3,7)
print(arr1)
arr2 = np.eye(5)*10
print(arr2)
arr3 = np.full((4,4),35,dtype='int32')
arr4 = np.eye(4,dtype='int32')*65
print(arr3+arr4)

[101 103 105 107 109 111 113 115 117 119 121 123 125 127 129]
[0.  0.5 1.  1.5 2.  2.5 3. ]
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]
[[100  35  35  35]
 [ 35 100  35  35]
 [ 35  35 100  35]
 [ 35  35  35 100]]


In [ ]:
present = np.array([22, 18, 25, 12, 20, 24, 9, 21, 17, 23])
print("first index:",present[0],"last index:",present[-1])
print()

first index: 22 last index: 23


IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed